### ISSUE TITLE
咨询一下：libtorch c++使用torch::jit::load(“best.pt”, device)异常

### ISSUE THREAD

**Issue by zhigaowu** [zeusees/SSD_License_Plate_Detection#47]
异常信息是：PytorchStreamReader failed locating file constants.pkl: file not found
请问一下：这个模型文件是要做什么处理吗？

**Comment by panda-lab** [comment]
是不是路径不对？你把模型的路径写成绝对路径试试？

**Comment by zhigaowu** [comment]
应该不是，我是用的是pt文件，这个pkl文件如果需要的话，也应该是pt内部的；
所以，我猜测这个pt的格式可能有点问题。
我使用onnx转换后的格式，使用tensorrt就没问题，可以正常使用
