### ISSUE TITLE
runs/train/exp/weights/last.pt不存在

### ISSUE THREAD

**Issue by Zane0227** [zeusees/SSD_License_Plate_Detection#49]
请问作者las.pt是如何生成的呢？是运行python train.py吗？

**Comment by Zane0227** [comment]
在运行python train.py时，widerface.yaml中/zeusee/data/yolov5-plate/data/widerface/train这个路径也不太清楚具体含义。感谢作者解惑

**Comment by SuperDickHead** [comment]
这明显是作者自己电脑里的路径啊，小撒刮

**Comment by Sencc** [comment]
@Zane0227 weights文件夹里面有模型文件，自行替换路径；train.py里的是训练集的路径

**Comment by Zane0227** [comment]
> @Zane0227 weights文件夹里面有模型文件，自行替换路径；train.py里的是训练集的路径

感谢！成功了~
